// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svtkehfvzrahtrkglxmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2dGtlaGZ2enJhaHRya2dseG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzkwNzQsImV4cCI6MjA1ODQxNTA3NH0.qdDKJgn8YAeIv0Dp2-bckCIF8bM6cK4qcZn9wE2rtTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);